/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BountyInterface extends Interface {
    getFunction(nameOrSignature: "amount" | "approveSubmission" | "cid" | "minStake" | "owner" | "rejectSubmission" | "reportCid" | "researcher" | "setMinStake" | "stakedAmount" | "status" | "submitReport"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FundsReleased" | "ReportSubmitted" | "StakeDeposited" | "StakeRefunded" | "StakeSlashed" | "SubmissionApproved" | "SubmissionRejected"): EventFragment;

    encodeFunctionData(functionFragment: 'amount', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveSubmission', values?: undefined): string;
encodeFunctionData(functionFragment: 'cid', values?: undefined): string;
encodeFunctionData(functionFragment: 'minStake', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'rejectSubmission', values?: undefined): string;
encodeFunctionData(functionFragment: 'reportCid', values?: undefined): string;
encodeFunctionData(functionFragment: 'researcher', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMinStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakedAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitReport', values: [string]): string;

    decodeFunctionResult(functionFragment: 'amount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reportCid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'researcher', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakedAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitReport', data: BytesLike): Result;
  }

  
    export namespace FundsReleasedEvent {
      export type InputTuple = [researcher: AddressLike, amount: BigNumberish];
      export type OutputTuple = [researcher: string, amount: bigint];
      export interface OutputObject {researcher: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReportSubmittedEvent {
      export type InputTuple = [researcher: AddressLike, reportCid: string];
      export type OutputTuple = [researcher: string, reportCid: string];
      export interface OutputObject {researcher: string, reportCid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeDepositedEvent {
      export type InputTuple = [researcher: AddressLike, amount: BigNumberish];
      export type OutputTuple = [researcher: string, amount: bigint];
      export interface OutputObject {researcher: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeRefundedEvent {
      export type InputTuple = [researcher: AddressLike, amount: BigNumberish];
      export type OutputTuple = [researcher: string, amount: bigint];
      export interface OutputObject {researcher: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeSlashedEvent {
      export type InputTuple = [researcher: AddressLike, amount: BigNumberish, receiver: AddressLike];
      export type OutputTuple = [researcher: string, amount: bigint, receiver: string];
      export interface OutputObject {researcher: string, amount: bigint, receiver: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmissionApprovedEvent {
      export type InputTuple = [researcher: AddressLike];
      export type OutputTuple = [researcher: string];
      export interface OutputObject {researcher: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmissionRejectedEvent {
      export type InputTuple = [researcher: AddressLike];
      export type OutputTuple = [researcher: string];
      export interface OutputObject {researcher: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Bounty extends BaseContract {
    
    connect(runner?: ContractRunner | null): Bounty;
    waitForDeployment(): Promise<this>;

    interface: BountyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    amount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approveSubmission: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    cid: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    minStake: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rejectSubmission: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reportCid: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    researcher: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setMinStake: TypedContractMethod<
      [_minStake: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakedAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submitReport: TypedContractMethod<
      [_reportCid: string, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'amount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approveSubmission'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cid'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'minStake'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rejectSubmission'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reportCid'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'researcher'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setMinStake'): TypedContractMethod<
      [_minStake: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakedAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitReport'): TypedContractMethod<
      [_reportCid: string, ],
      [void],
      'payable'
    >;

    getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'ReportSubmitted'): TypedContractEvent<ReportSubmittedEvent.InputTuple, ReportSubmittedEvent.OutputTuple, ReportSubmittedEvent.OutputObject>;
getEvent(key: 'StakeDeposited'): TypedContractEvent<StakeDepositedEvent.InputTuple, StakeDepositedEvent.OutputTuple, StakeDepositedEvent.OutputObject>;
getEvent(key: 'StakeRefunded'): TypedContractEvent<StakeRefundedEvent.InputTuple, StakeRefundedEvent.OutputTuple, StakeRefundedEvent.OutputObject>;
getEvent(key: 'StakeSlashed'): TypedContractEvent<StakeSlashedEvent.InputTuple, StakeSlashedEvent.OutputTuple, StakeSlashedEvent.OutputObject>;
getEvent(key: 'SubmissionApproved'): TypedContractEvent<SubmissionApprovedEvent.InputTuple, SubmissionApprovedEvent.OutputTuple, SubmissionApprovedEvent.OutputObject>;
getEvent(key: 'SubmissionRejected'): TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;

    filters: {
      
      'FundsReleased(address,uint256)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'ReportSubmitted(address,string)': TypedContractEvent<ReportSubmittedEvent.InputTuple, ReportSubmittedEvent.OutputTuple, ReportSubmittedEvent.OutputObject>;
      ReportSubmitted: TypedContractEvent<ReportSubmittedEvent.InputTuple, ReportSubmittedEvent.OutputTuple, ReportSubmittedEvent.OutputObject>;
    

      'StakeDeposited(address,uint256)': TypedContractEvent<StakeDepositedEvent.InputTuple, StakeDepositedEvent.OutputTuple, StakeDepositedEvent.OutputObject>;
      StakeDeposited: TypedContractEvent<StakeDepositedEvent.InputTuple, StakeDepositedEvent.OutputTuple, StakeDepositedEvent.OutputObject>;
    

      'StakeRefunded(address,uint256)': TypedContractEvent<StakeRefundedEvent.InputTuple, StakeRefundedEvent.OutputTuple, StakeRefundedEvent.OutputObject>;
      StakeRefunded: TypedContractEvent<StakeRefundedEvent.InputTuple, StakeRefundedEvent.OutputTuple, StakeRefundedEvent.OutputObject>;
    

      'StakeSlashed(address,uint256,address)': TypedContractEvent<StakeSlashedEvent.InputTuple, StakeSlashedEvent.OutputTuple, StakeSlashedEvent.OutputObject>;
      StakeSlashed: TypedContractEvent<StakeSlashedEvent.InputTuple, StakeSlashedEvent.OutputTuple, StakeSlashedEvent.OutputObject>;
    

      'SubmissionApproved(address)': TypedContractEvent<SubmissionApprovedEvent.InputTuple, SubmissionApprovedEvent.OutputTuple, SubmissionApprovedEvent.OutputObject>;
      SubmissionApproved: TypedContractEvent<SubmissionApprovedEvent.InputTuple, SubmissionApprovedEvent.OutputTuple, SubmissionApprovedEvent.OutputObject>;
    

      'SubmissionRejected(address)': TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
      SubmissionRejected: TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
    
    };
  }